### PR TITLE
Update references according to APA

### PR DESCRIPTION
**Pull request by MargaritaRad**

### CODE REVIEW

**Comment by loikein** [comment]
I'm wondering, why all the links?

If no particular reason, is it possible to align with [Bibliography](https://econsa.readthedocs.io/en/latest/bibliography.html)? @MargaritaRad

**Comment by MargaritaRad** [comment]
Well, did not add the links myself, I would ask Philipp if he wants to keep them as he did not mention it in the meeting, could you please tag and ask him? Thank you!

**Comment by loikein** [comment]
Ok let's just remove the links… keep the DOIs if it's not too much work.

**Comment by MargaritaRad** [comment]
So, shall we enter DOI-Links on the place of the existing links?

**Comment by loikein** [comment]
No links in the entry, and if there is a DOI link, put it after the entry. Take a look at [Bibliography — econsa 0.01 documentation](https://econsa.readthedocs.io/en/latest/bibliography.html) to get some ideas…

**Comment by MargaritaRad** [comment]
Ah, I see! Thanks a lot! Will do that, then. Is tomorrow morning fine? From: LeiqiongSent: 15 July 2020 19:30To: OpenSourceEconomics/econsaCc: Margarita Rad; MentionSubject: Re: [OpenSourceEconomics/econsa] Update references according to APA (#46) No links in the entry, and if there is a DOI link, put it after the entry. Take a look at Bibliography — econsa 0.01 documentation to get some ideas…—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by loikein** [comment]
Thank you! I have changed the due date on ClickUp.

**Comment by MargaritaRad** [comment]
Thank you very much! From: LeiqiongSent: 15 July 2020 19:36To: OpenSourceEconomics/econsaCc: Margarita Rad; MentionSubject: Re: [OpenSourceEconomics/econsa] Update references according to APA (#46) Thank you! I have changed the due date on ClickUp.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by loikein** [comment]
Replaced by [#47](https://github.com/OpenSourceEconomics/econsa/pull/47).

**Pull request closed without merging**
