### PR TITLE
Debugging workflow: rearrange dependencies; bump rpy2 version; use mamba

### PR DESCRIPTION
**Pull request by loikein**
Previously… [Cannot uninstall/update package (via pip) on Windows · Issue #88 · conda-incubator/setup-miniconda](https://github.com/conda-incubator/setup-miniconda/issues/88)

Pip flags should work but they don't: [Allow pip requirements.txt syntax in environment files by sdvillal · Pull Request #3969 · conda/conda](https://github.com/conda/conda/pull/3969)

[It is recommended](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#using-pip-in-an-environment) that we avoid `pip --user` in conda enviornment, which I don't understand, but ok.

### CODE REVIEW

**Comment by loikein** [comment]
For my information… https://github.com/conda-incubator/setup-miniconda/issues/88

**Comment by loikein** [comment]
For my information: https://github.com/conda/conda/pull/3969

**Comment by loikein** [comment]
I guess the lesson here is to avoid pip as much as possible.

**Comment by loikein** [comment]
Reminder: the main goal here is to get Python 3.7 to work. Package conflicts can wait.

**Comment by loikein** [comment]
<details><summary>Output of my current`conda list`</summary>

```bash
# packages in environment at /opt/miniconda3/envs/econsa:
#
# Name                    Version                   Build  Channel
_r-mutex                  1.0.1               anacondar_1    conda-forge
alabaster                 0.7.12                   py37_0
algopy                    0.5.7                      py_0    conda-forge
appdirs                   1.4.4                      py_0
appnope                   0.1.0                    py37_0
argon2-cffi               20.1.0           py37haf1e3a3_1
async_generator           1.10             py37h28b3542_0
attrs                     20.2.0                     py_0
babel                     2.8.0                      py_0
backcall                  0.2.0                      py_0
black                     21.4b0             pyhd8ed1ab_0    conda-forge
black-nb                  0.5.0                    pypi_0    pypi
bleach                    3.2.1                      py_0
bokeh                     2.2.3                    py37_0
brotlipy                  0.7.0           py37haf1e3a3_1000
bwidget                   1.9.14                        0    conda-forge
bzip2                     1.0.8                h1de35cc_0
c-ares                    1.16.1               haf1e3a3_0
ca-certificates           2021.5.30            h033912b_0    conda-forge
cairo                     1.16.0            ha8983da_1005    conda-forge
cairocffi                 1.2.0                    pypi_0    pypi
cairosvg                  2.5.2                    pypi_0    pypi
cctools_osx-64            949.0.1             h8e49ea9_16    conda-forge
certifi                   2021.5.30        py37hecd8cb5_0
cffi                      1.14.3           py37hed5b41f_0
cfgv                      3.2.0                      py_0    conda-forge
chaospy                   3.3.8                      py_0    conda-forge
chardet                   3.0.4                 py37_1003
clang                     10.0.1          default_hf57f61e_1    conda-forge
clang_osx-64              10.0.1              h05bbb7f_10    conda-forge
clangxx                   10.0.1          default_hf57f61e_1    conda-forge
clangxx_osx-64            10.0.1              h05bbb7f_10    conda-forge
click                     7.1.2                      py_0
colorama                  0.4.4              pyhd3eb1b0_0
compiler-rt               10.0.1               he6db49b_0    conda-forge
compiler-rt_osx-64        10.0.1               h033240e_0    conda-forge
coverage                  5.3              py37haf1e3a3_0
cryptography              3.2              py37h55b06a8_0    conda-forge
cssselect2                0.4.1                    pypi_0    pypi
curl                      7.71.1               hcb81553_8    conda-forge
cycler                    0.10.0                   py37_0
dataclasses               0.7                      py37_0
dbus                      1.13.18              h18a8e69_0
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
distlib                   0.3.1                    py37_0
docutils                  0.16                     py37_1
editdistance              0.5.3            py37hdadc0f0_2    conda-forge
entrypoints               0.3                      py37_0
expat                     2.2.10               hb1e8313_2
fancycompleter            0.9.1           py37hc8dfbb8_1002    conda-forge
filelock                  3.0.12                     py_0
flake8                    3.8.4                      py_0
flake8-nb                 0.3.0                    pypi_0    pypi
fontconfig                2.13.1            h79c0d67_1002    conda-forge
freetype                  2.10.4               ha233b18_0
fribidi                   1.0.10               haf1e3a3_0
gettext                   0.19.8.1             hb0f4f8b_2
gfortran_impl_osx-64      7.5.0                hae4d780_7    conda-forge
gfortran_osx-64           7.5.0                h044cb63_8    conda-forge
glib                      2.66.1               h9bbe63b_0
gmp                       6.2.0                hb1e8313_3    conda-forge
graphite2                 1.3.14               h38d11af_0
gsl                       2.6                  ha2d443c_0    conda-forge
harfbuzz                  2.7.2                h8810732_0    conda-forge
hypothesis                6.14.0             pyhd8ed1ab_0    conda-forge
icu                       67.1                 hb1e8313_0    conda-forge
identify                  1.5.6              pyh9f0ad1d_0    conda-forge
idna                      2.10                       py_0
imagesize                 1.2.0                      py_0
importlib-metadata        4.5.0                    pypi_0    pypi
importlib_metadata        2.0.0                         1
iniconfig                 1.1.1              pyhd3eb1b0_0
ipykernel                 5.5.5            py37h85f7c60_0    conda-forge
ipython                   7.18.1           py37h5ca1d4c_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.5.1                      py_1
isl                       0.22.1               hb1e8313_2    conda-forge
isort                     5.6.4                      py_0
jedi                      0.17.2                   py37_0
jinja2                    2.11.2                     py_0
joblib                    0.17.0                     py_0
jpeg                      9d                   h0b31af3_0    conda-forge
json5                     0.9.5                      py_0
jsonschema                3.2.0                      py_2
jupyter                   1.0.0                    py37_7
jupyter_client            6.1.7                      py_0
jupyter_console           6.2.0                      py_0
jupyter_core              4.6.3                    py37_0
jupyterlab                2.3.1              pyhd3eb1b0_0
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         1.2.0                      py_0
kiwisolver                1.3.0            py37h23ab428_0
krb5                      1.17.1               hddcf347_0
latexcodec                2.0.1              pyh9f0ad1d_0    conda-forge
lcms2                     2.11                 h92f6f08_0
ld64_osx-64               530                  h3c32e8a_7    conda-forge
ldid                      2.1.2                h7660a38_2    conda-forge
libblas                   3.9.0                2_openblas    conda-forge
libcblas                  3.9.0                2_openblas    conda-forge
libclang                  10.0.1          default_hf57f61e_1    conda-forge
libclang-cpp10            10.0.1          default_hf57f61e_1    conda-forge
libcurl                   7.71.1               h9bf37e3_8    conda-forge
libcxx                    11.0.0               h439d374_0    conda-forge
libedit                   3.1.20191231         h1de35cc_1
libev                     4.33                 haf1e3a3_0
libffi                    3.3                  hb1e8313_2
libgfortran               4.0.0               h50e675f_13    conda-forge
libgfortran4              7.5.0               h50e675f_13    conda-forge
libiconv                  1.16                 h1de35cc_0
liblapack                 3.9.0                2_openblas    conda-forge
libllvm10                 10.0.1               h76017ad_5
libllvm11                 11.0.0               hf85e3d2_0    conda-forge
libnghttp2                1.41.0               h7580e61_2
libopenblas               0.3.12          openmp_h63d9170_1    conda-forge
libpng                    1.6.37               ha441bb4_0
libpq                     12.3                 haa216e0_2    conda-forge
libsodium                 1.0.18               h1de35cc_0
libssh2                   1.9.0                ha12b0ac_1
libtiff                   4.1.0                hcb84e12_1
libxml2                   2.9.10               h2c6e4a5_2    conda-forge
llvm-openmp               11.0.0               h73239a0_1    conda-forge
llvm-tools                10.0.1               h40edb58_5
llvmlite                  0.34.0           py37h739e7dc_4
lz4-c                     1.9.2                h79c402e_3
make                      4.3                  h22f3db7_1    conda-forge
markupsafe                1.1.1            py37h1de35cc_0
matplotlib                3.3.2                         0
matplotlib-base           3.3.2            py37h181983e_0
mccabe                    0.6.1                    py37_1
mistune                   0.8.4            py37h1de35cc_0
more-itertools            8.6.0              pyhd8ed1ab_0    conda-forge
mpc                       1.1.0                h6ef4df4_1
mpfr                      4.0.2                h9066e36_1
mypy_extensions           0.4.3                    py37_0
mysql-common              8.0.21                        2    conda-forge
mysql-libs                8.0.21               hfb8f7af_2    conda-forge
nbclient                  0.5.1                      py_0
nbconvert                 6.0.7                    py37_0
nbformat                  5.0.8                      py_0
nbsphinx                  0.8.6              pyhd8ed1ab_1    conda-forge
ncurses                   6.2                  h0a44026_1
nest-asyncio              1.4.1                      py_0
networkx                  2.5                        py_0
nodeenv                   1.5.0              pyh9f0ad1d_0    conda-forge
notebook                  6.1.4                    py37_0
nspr                      4.29                 hb1e8313_1    conda-forge
nss                       3.47                 hc0980d9_0    conda-forge
numba                     0.51.2           py37h959d312_1
numdifftools              0.9.39                     py_0    conda-forge
numpoly                   1.0.8              pyhd8ed1ab_0    conda-forge
numpy                     1.20.3           py37h84c02c4_1    conda-forge
numpydoc                  1.1.0              pyhd3eb1b0_1
olefile                   0.46                     py37_0
openssl                   1.1.1k               h9ed2024_0
oset                      0.1.3                      py_1    conda-forge
packaging                 20.4                       py_0
pandas                    1.2.4            py37h23ab428_0
pandoc                    2.11.0.4             h22f3db7_0    conda-forge
pandocfilters             1.4.2                    py37_1
pango                     1.42.4               hc249df1_1
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
pathspec                  0.8.0              pyh9f0ad1d_0    conda-forge
patsy                     0.5.1                    py37_0
pcre                      8.44                 hb1e8313_0
pdbpp                     0.10.0                     py_0    conda-forge
pexpect                   4.8.0                    py37_0
pickleshare               0.7.5                    py37_0
pillow                    8.0.1            py37h5270095_0
pip                       21.1.2           py37hecd8cb5_0
pixman                    0.38.0               h1de35cc_0
pluggy                    0.13.1                   py37_0
pre-commit                2.13.0           py37hf985489_0    conda-forge
prometheus_client         0.8.0                      py_0
prompt-toolkit            3.0.8                      py_0
prompt_toolkit            3.0.8                         0
ptyprocess                0.6.0                    py37_0
py                        1.9.0                      py_0
pybtex                    0.23.0           py37hc8dfbb8_0    conda-forge
pybtex-docutils           0.2.2            py37hc8dfbb8_2    conda-forge
pycodestyle               2.6.0                      py_0
pycparser                 2.20                       py_2
pyflakes                  2.2.0                      py_0
pygments                  2.7.2              pyhd3eb1b0_0
pyopenssl                 19.1.0                     py_1
pyparsing                 2.4.7                      py_0
pyqt                      5.12.3           py37h25ebb8a_4    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrepl                    0.9.0            py37h60d8a13_2    conda-forge
pyrsistent                0.17.3           py37haf1e3a3_0
pysocks                   1.7.1                    py37_0
pytest                    6.2.4            py37hf985489_0    conda-forge
pytest-black              0.3.12                     py_0    conda-forge
pytest-cov                2.12.1             pyhd8ed1ab_0    conda-forge
pytest-flake8             1.0.7              pyhd3eb1b0_0
pytest-randomly           3.8.0                    pypi_0    pypi
pytest-stress             1.0.1                    pypi_0    pypi
pytest-sugar              0.9.4              pyh9f0ad1d_1    conda-forge
python                    3.7.10               h88f2d9e_0
python-dateutil           2.8.1                      py_0
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1                     py_0
pyyaml                    5.3.1            py37haf1e3a3_1
pyzmq                     19.0.2           py37hb1e8313_1
qt                        5.12.9               h717870c_0    conda-forge
qtconsole                 4.7.7                      py_0
qtpy                      1.9.0                      py_0
r-assertthat              0.2.1             r36h6115d3f_0
r-backports               1.1.10            r36h800e0f2_0    conda-forge
r-base                    3.6.3                hc30ca75_3    conda-forge
r-bit                     4.0.4             r36h800e0f2_0    conda-forge
r-bit64                   4.0.5             r36h800e0f2_0    conda-forge
r-blob                    1.2.1             r36h6115d3f_1    conda-forge
r-cli                     2.1.0             r36h142f84f_0    conda-forge
r-condmvnorm              2015.2_1          r36h6115d3f_0
r-crayon                  1.3.4             r36h6115d3f_0
r-dbi                     1.1.0             r36h6115d3f_1    conda-forge
r-dbplyr                  1.4.4             r36h6115d3f_0    conda-forge
r-digest                  0.6.27            r36h342fd00_0    conda-forge
r-dplyr                   1.0.2             r36h710217c_0    conda-forge
r-ellipsis                0.3.1             r36h17f1fa6_0    conda-forge
r-fansi                   0.4.1             r36h17f1fa6_1    conda-forge
r-generics                0.1.0             r36hc72bb7e_0    conda-forge
r-glue                    1.4.2             r36h800e0f2_0    conda-forge
r-lifecycle               0.2.0             r36h6115d3f_1    conda-forge
r-magrittr                1.5               r36h6115d3f_4
r-memoise                 1.1.0             r36h6115d3f_0
r-mvtnorm                 1.1_1             r36ha752707_1    conda-forge
r-pillar                  1.4.6             r36h6115d3f_0    conda-forge
r-pkgconfig               2.0.3             r36h6115d3f_1    conda-forge
r-plogr                   0.2.0             r36h6115d3f_0
r-purrr                   0.3.4             r36h17f1fa6_1    conda-forge
r-r.methodss3             1.8.1             r36h6115d3f_0    conda-forge
r-r.oo                    1.24.0            r36h6115d3f_0    conda-forge
r-r.utils                 2.10.1            r36h6115d3f_0    conda-forge
r-r6                      2.5.0             r36hc72bb7e_0    conda-forge
r-rcpp                    1.0.5             r36hc5da6b9_0    conda-forge
r-rlang                   0.4.7             r36h17f1fa6_0    conda-forge
r-rsqlite                 2.2.1             r36h342fd00_0    conda-forge
r-tibble                  3.0.4             r36hb5ad454_0    conda-forge
r-tidyselect              1.1.0             r36h6115d3f_0    conda-forge
r-utf8                    1.1.4             r36h46e59ec_0
r-vctrs                   0.3.4             r36h800e0f2_0    conda-forge
r-zeallot                 0.1.0             r36h6115d3f_0
readline                  8.0                  h1de35cc_0
regex                     2020.10.28       py37h4b544eb_0    conda-forge
requests                  2.24.0                     py_0
rpy2                      2.9.4           py37r36h1d22016_0
scikit-learn              0.23.2           py37h959d312_0
scipy                     1.5.3            py37h04d6967_0    conda-forge
seaborn                   0.11.1             pyhd3eb1b0_0
send2trash                1.5.0                    py37_0
setuptools                50.3.0           py37h0dc7051_1
six                       1.15.0                     py_0
snowballstemmer           2.0.0                      py_0
sortedcontainers          2.2.2                      py_0
sphinx                    4.0.2              pyh6c4a22f_1    conda-forge
sphinx_rtd_theme          0.5.2              pyhd8ed1ab_1    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0
sphinxcontrib-bibtex      1.0.0                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0
sphinxcontrib-htmlhelp    1.0.3                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.3                      py_0
sphinxcontrib-serializinghtml 1.1.4                      py_0
sphinxcontrib-svg2pdfconverter 1.1.1                    pypi_0    pypi
sqlite                    3.33.0               hffcf06c_0
statsmodels               0.12.2           py37h9ed2024_0
tapi                      1000.10.8            ha1b3eb9_0
temfpy                    1.1.4                      py_0    opensourceeconomics
termcolor                 1.1.0                    py37_1
terminado                 0.9.1                    py37_0
testpath                  0.4.4                      py_0
threadpoolctl             2.1.0              pyh5ca1d4c_0
tinycss2                  1.1.0                    pypi_0    pypi
tk                        8.6.10               hb0a8c7a_0
tktable                   2.10                 h1de35cc_0
toml                      0.10.1                     py_0
tornado                   6.1              py37h4b544eb_0    conda-forge
traitlets                 5.0.5                      py_0
typed-ast                 1.4.3            py37h271585c_0    conda-forge
typing_extensions         3.7.4.3                    py_0
urllib3                   1.25.11                    py_0
virtualenv                20.1.0           py37hc8dfbb8_0    conda-forge
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py37_1
wheel                     0.35.1                     py_0
widgetsnbextension        3.5.1                    py37_0
wmctrl                    0.3             py37hc8dfbb8_1002    conda-forge
xz                        5.2.5                h1de35cc_0
yaml                      0.2.5                haf1e3a3_0
zeromq                    4.3.3                hb1e8313_3
zipp                      3.4.0              pyhd3eb1b0_0
zlib                      1.2.11               h1de35cc_3
zstd                      1.4.5                h41d2c2f_0
```

</details>

**Comment by loikein** [comment]
> Reminder: the main goal here is to get Python 3.7 to work. Package conflicts can wait.

Ok, that is done.

**Comment by loikein** [comment]
Move onto package conflicts. Can confirm when setting `python=3.8`, the environment cannot be installed on my machine.

**Comment by loikein** [comment]
I will force, or rather sneak in, the move towards [Mamba](https://mamba.readthedocs.io/en/latest/index.html) and nobody's gonna stop me.

**Comment by loikein** [comment]
Turns out rpy v2.9.4 only works with Python 3.7, will have to find a way to test some newer version…

**Comment by loikein** [comment]
↑ Manual tag: best working version for Python 3.7 so far.

**Comment by loikein** [comment]
@bhmueller Please try out the latest version of files, I tried my best to make everything work.

**Review by peisenha — APPROVED** [review]
Thanks for the fixup!

**Pull request merged**
