### PR TITLE
Follow packaging guide

### PR DESCRIPTION
**Pull request by loikein**
Source: [OpenSourceEconomics/packaging-guide: A guide to Python packages.](https://github.com/OpenSourceEconomics/packaging-guide)

### CODE REVIEW

**Comment by loikein** [comment]
I have no knowledge of Windows now. Any thoughts? @peisenha @tobiasraabe

**Comment by peisenha** [comment]
@loikein , thanks for getting it mostly up and running. @tobiasraabe , as our resident Windows expert can you please have a look. If we need to get rid of the `.envrc` file setup for this that is fine. We have big plans for `econsa` and want to pick up our audience where they are :smile:

**Comment by tobiasraabe** [comment]
I would remove the `.envrc`. I think it is very specific to your setup.

If you need a script that generates figures for your docs, it is not necessary to run it every time. Or make a test for it.

You can also update the pre-commit-hooks with the example provided in the packaging guide.

**Comment by peisenha** [comment]
I prefer to have the figure running each time, it helps very much to only get PRs assigned that did properly update any requires changes going forward there as well. If that is a major issue to get to run on Windows, we could just only have it run under Ubuntu?

**Comment by tobiasraabe** [comment]
Yes, should be possible.

The export command probably does not work. It has some nice to have features, so it should not do any harm if it does not work.

**Comment by peisenha** [comment]
@loikein , then let us do that just remove the failing scripts from the Windows build.

**Comment by loikein** [comment]
For windows, the problem is not `.envrc`, but the `run-figures`. It seems to not be able to find our figure script.

```
/d/a/econsa/econsa/bin/run-figures: line 1: ../scripts/run_figures.py: No such file or directory
```

**Comment by loikein** [comment]
> You can also update the pre-commit-hooks with the example provided in the packaging guide.

You seem to have removed the example file from that repo. Please take a look…

**Comment by tobiasraabe** [comment]
Classic error on my side. Forgot to add the file 🤦

**Comment by loikein** [comment]
Why do you squash all the commits into one commit? I don't think it's a good habit, considering using git is for version control.

**Comment by tobiasraabe** [comment]
I do it for the packaging guide, because I do not want to pollute the commit history right from the start. It is not necessary to use vcs at this point. Thus, it is perfectly fine in this case. Or do you refer to the general practice of squashing all commits of one PR.

Some of their settings are specific to their repo. If you feel like they have a hook which is useful in general and for the packaging guide, write me via Zulip and I will add it.

**Comment by loikein** [comment]
> It is not necessary to use vcs at this point.

Oh, then we have some conceptual differences. I will respect your decision, but had you not do that, it would be possible to look into the history and found lost files without effort on your side.

On the settings over econ-project-templates, I am trying to tweak some args according to that. For example, `'--maxkb=100'` may be too small since there will be figures.

**Comment by tobiasraabe** [comment]
I think we have a misunderstanding and not a conceptual difference. A file which has not been committed to a repository before, cannot be lost or recovered from the git history. It simply lies in the local copy of the repo waiting to be added.

**Comment by loikein** [comment]
I see. Then, had you used multiple commits, I would have know that as well. In short, I think that version control is necessary from the beginning. Myself squash commits too, but only when they are really dealing with the same thing and are trivial.

**Comment by loikein** [comment]
@peisenha Oh my, I cannot merge now. Would you please do the job?

**Comment by loikein** [comment]
Main steps to implement:

1. Put a `.pre-commit-config.yaml` at the root of repo.
1. Add `pre-commit` to `environment.yml`, under the `pip` section.
1. Run `conda env update`
1. Run `pre-commit install`
1. Run `pre-commit run --all-files` to check all existing files.
1. Check & fix the errors, and maybe adjust some pre-commit settings. (E.g. file size restriction may vary between repos, etc.)  
Note: If you added some new hooks, pre-commit will need to re-configure the enviornment, may take several minutes.
1. Repeat. After all tests passed, add run pre-commit job to `.github/workflows/ci.yml`.
1. Push and see if the tests pass.   
Note: If you found some little bug and pushed a new version after a short period of time, you may want to cancel the current running CI tests to start new tests.

**Comment by loikein** [comment]
Main steps to implement multiple OS for CI tests:

1. Non of the OS's recognises `source activate` in `.envrc`, so you either don't use it at all (may cause other problems consequently) or make a `.envrc-ci` without that command.
1. Adjust `.github/workflows/ci.yml` according to [packaging-guide/ci-with-codecov.yaml](https://github.com/OpenSourceEconomics/packaging-guide/blob/master/.github/workflows/ci-with-codecov.yaml).  
During that, some notes:
    1. This part: `uses: goanpeca/setup-miniconda@v1.0.2` prepares all OS's for conda, and also **activates the current environment**, so you don't need to think about it whatsoever.
    1. Uploading to Codecov only needs to be done once, so you may want to specify both OS & Python version.
    1. Our current way to upload to Codecov is more simple and potentially more robust to different OS's. (`uses: codecov/codecov-action@v1`) (cc @tobiasraabe )
    1. Since `econsa` only officially support Python 3.7, I didn't include Python 3.6, but this may vary between repos.
    1. The `run-figures` script does not work with Windows. If you have a solution, please tell me and make a PR; if you have no idea, just skip it.
    1. The same applies to pre-commit hooks.

**Comment by loikein** [comment]
I have commented above my review of making this PR. Please take a look for implementing the packaging guide elsewhere. 

cc @peisenha @milakis @luward (Who else may want to be mentioned? You could edit this comment to include them.)

**Pull request merged**
